version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: task-manager-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: taskdb-test
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  mongo-data:


