version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: task-manager-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: taskdb-test
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  task-runner:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/scripts/generate-tasks.js
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongodb:27017/taskdb
    depends_on:
      - mongodb
      - redis
  task_manager_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongodb:27017/taskdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongodb
      - redis
      - task-runner

volumes:
  mongo-data:


