version: '3.8'

services:
  task_manager_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:6.0
    container_name: task-manager-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: taskdb-test
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:


